<div class="bs-docs-section">
    <div class="well">

        <?php
        $id = explode('/', $_SERVER['REQUEST_URI'])[4];
        $form->setAttribute('action', $this->url('admin/article', ['action' => 'edit', 'id' => $id]));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo '<fieldset><legend>Редактирование статьи</legend>';
        foreach ($form as $element){
            echo '<div class="form-group">';
            $attr = $element->getAttributes();
            if ($element->getLabel()){
                $element->setLabelAttributes(['class' => 'col-lg-2 control-label']);
                $label = $element->getLabel();
                if (isset($attr['required'])){
                    $element->setLabel($element->getLabel() . ' *');
                }
                $label = "<label class='col-lg-2 control-label'>{$label}</label>";
            }
            $type = isset($attr['type']) ?  $attr['type'] : '';
            $formElement = '';
            switch ($type){
                case 'text':
                    $formElement = $this->formInput($element);
                    break;
                case 'textarea':
                    $formElement = $this->formTextArea($element);
                    break;
                case 'select':
                    $formElement = $this->formSelect($element);
                    break;
                default:
                    $formElement = $this->formRow($element);
                    $label = ''; break;
            }
            echo "{$label} <div class='col-lg-10'>{$formElement}</div>";
            echo "</div>";
        }
        echo '</<fieldset>';
        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<script src="/js/ckeditor/ckeditor.js"></script>