<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;
$r->headLink()->appendStylesheet('/css/filterPassport.css');
$d = date('Y-m-d');
?>
<form method='post' class='filter' action="/passport/all/?post=1">
    <div class="col-lg-11">
    <fieldset>
        <legend>Выберите тип изделия: </legend>
        <label class="radio-inline"><input type="radio" name="type" value="Завесы">Завесы</label><br>
        <label class="radio-inline"><input type="radio" name="type" value="Тепловентиляторы">Тепловентиляторы</label><br>
        <label class="radio-inline"><input type="radio" name="type" value="Фанкойлы">Фанкойлы</label><br>
    </fieldset>
    <fieldset>
        <legend>Выберите источник тепла: </legend>
        <label class="checkbox-inline"><input type="checkbox" name="EWA[]" value="E">E</label>
        <label class="checkbox-inline"><input type="checkbox" name="EWA[]" value="W">W</label>
        <label class="checkbox-inline"><input type="checkbox" name="EWA[]" value="A">A</label>
        <label class="checkbox-inline"><input type="checkbox" name="EWA[]" value="G">G</label><br>
    </fieldset>

    <fieldset style="color: #000;">
        <legend>Выберите серию: </legend>
        <select class="col-lg-12" id="seria" name="seria">
            <?php foreach ($this->series as $seria) {
                echo "<option>{$seria}</option>";
            } ?>
        </select>
    </fieldset>

    <fieldset>
        <legend>Статус: </legend>
        <?php foreach ($this->status as $item) {?>
            <label><input type="radio" name="status" value="<?=$item?>">&nbsp;<?=$item?></label>&nbsp;
        <?php } ?>
    </fieldset>

    <fieldset>
        <legend>Редакция: </legend>
        <div class="col-lg-5" style="padding: 0;"><input type="date" style="width: 100%;" min="2017-04-01" name="start" value="2017-04-01"></div>
        <div class="col-lg-2" style="text-align: center;">до</div>
        <div class="col-lg-5" style="padding: 0;"><input type="date" style="width: 100%;" name="end" value="<?=$d?>"></div>
    </fieldset>
    <br>

    <div style="margin: auto;">
        <input class="btn btn-success" style="float: right;" type="submit" value='Найти паспорт'>
    </div>
    </div>
</form>