<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;
$this->headLink()->appendStylesheet('/css/btnstyle.css');
//$bv = new \Custom\BaseView($r, 'main', 'container');
//$bv->addInCol()
//echo $r->partial('sidebar.phtml');
//echo "<div style='float: left;'>";
//if(isset($desc)) echo "<h2>{$desc}</h2>";
$this->fm->pr();
$this->q->prTable();
$e = $this->paginationControl($this->name, 'Sliding', 'pagination_control', ['route' => $this->route]);
$e = str_replace('?page', $this->table.'&page', $e);
echo $e;
//echo '<div class="breadcrumbs hi"> <br>'. $this->navigation('Zend\\Navigation\\Admin_navigation')->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render() . '</div>';
$this->headScript()->appendFile('/js/btnstyle.js');
?>