<?php if ($this->pageCount){ ?>
    <ul class="pagination pagination-sm">
    <?php if (isset($this->previous)){ ?>
        <li><a href="<?php if ($this->url($this->route)){ ?>?page=<?php echo $this->previous; ?>"><<</a></li>
        <?php }?>
    <?php } else { ?>
    <li class="disabled"><a href="#" onclick="return false"><<</a></li>
        <?php }?>
    <?php foreach ($this->pagesInRange as $page) { ?>
        <?php if($page != $this->current){ ?>
        <li><a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>"><?= $page ?></a></li>
        <?php } else { ?>
            <li class="active"><a href="#"><?=$page;?></a></li>
        <?php } ?>
    <?php } ?>
        <?php if (isset($this->next)){ ?>
            <li><a href="<?php if ($this->url($this->route)){ ?>?page=<?php echo $this->next; ?>">>></a></li>
            <?php }?>
            <?php } else { ?>
                <li class="disabled"><a href="#" onclick="return false">>></a></li>
        <?php }?>
    </ul>
<?php } ?>