<th style="width: 15mm; border: 1px solid black; font-weight: bold;">№</th>
<th style="width: 25mm; border: 1px solid black; font-weight: bold;">Дата</th>
<th style="width: 45mm; border: 1px solid black; font-weight: bold;">Чертеж</th>
<th style="width: 50mm; border: 1px solid black; font-weight: bold;">Тип изделия</th>
<th style="width: 15mm; border: 1px solid black; font-weight: bold;">Кол-во</th>
<th style="width: 70mm; border: 1px solid black; font-weight: bold;">Описание дефекта</th>
<th style="width: 65mm; border: 1px solid black; font-weight: bold;">Заключение</th>