<tr>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->number)?></td>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->date)?></td>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->drawing)?></td>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->type)?></td>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->count)?></td>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->name[0])?></td>
    <td style=" border: 1px solid black"><?=$this->EscapeHtml($this->name[1])?></td>
</tr>