<?php
/**
 * Created by PhpStorm.
 * User: Simanov
 * Date: 20.10.2017
 * Time: 11:13
 */

namespace Custom;


use Doctrine\ORM\EntityManager;
use Zend\Authentication\AuthenticationService;
use Zend\Http\Request;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

class BaseAdminController extends AbstractActionController
{
    /**
     * @var EntityManager
     */
    protected $entityManager;
    /**
     * @var FlashMsgr
     */
    protected $fm;
    /**
     * @var
     */
    protected $id;
    /**
     * @var Request
     */
    protected $req;
    /**
     * @var MyForm
     */
    public $form;
    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    public function getFm(FlashMessenger $flashMessenger){
        $this->fm = new FlashMsgr($flashMessenger);
    }
    public function addMsg($message)
    {
        $this->fm->add($message);
    }
    public function getId()
    {
        return $this->id = $this->params()->fromRoute('id',0);
    }
    public function redir($path)
    {
        return $this->redirect()->toRoute($path);
    }
    public function getReq()
    {
        return $this->req = $this->getRequest();
    }
    public function error($message)
    {
        $this->fm->status = 'error';
        $msg = $message;
        foreach ($this->form->getForm()->getInputFilter()->getInvalidInput() as $errors) {
            foreach ($errors->getMessages() as $error){
                $msg .= ' ' . $error;
            }
        }
        $this->fm->add($msg);
    }
    public function getItem($arr)
    {
        $id = $this->getId();
        $r = $this->entityManager->getRepository($arr['Entity']);
        $item = $r->find($id);
        if(empty($item)){
            $this->fm->status = 'error';
            $this->fm->add($arr['MessageError']);
            $this->redir($arr['Redirect']);
            return null;
        }
        return $item;
    }
    public function add($arr)
    {
        $fields = new $arr['Entity']();
        $this->form = new MyForm($fields, $this->entityManager);
        $this->getReq();
        $this->form->setAction($arr['Action']);
        if ($this->req->isPost()){
            $this->form->setData($this->req->getPost());
            if ($this->form->getForm()->isValid()){
                $this->entityManager->persist($fields);
                $this->entityManager->flush();
                $this->fm->add($arr['MessageSuccess']);
            } else {
                $this->error($arr['MessageError']);
            }
        } else {
            $this->form->getForm()->prepare();
            return ['form' => $this->form, 'id' => $this->id];
        }
        $this->redir($arr['Redirect']);
        return null;
    }
    public function edit($arr)
    {
        $fields = new $arr['Entity']();
        $item = $this->getItem($arr);
        $this->form = new MyForm($fields, $this->entityManager);
        $this->form->getForm()->bind($item);
        $this->req = $this->getReq();
        if($this->req->isPost()){
            $this->form->setData($this->req->getPost());
            if($this->form->getForm()->isValid()){
                $this->entityManager->persist($item);
                $this->entityManager->flush();
                $this->fm->add($arr['MessageSuccess']);
            } else {
                $this->error($arr['MessageError']);
            }
        } else {
            $this->form->getForm()->prepare();
            return ['form' => $this->form, 'id' => $this->id];
        }
        $this->redir($arr['Redirect']);
        return null;
    }
    public function delete($arr)
    {
        try {
            $item = $this->getItem($arr);
            $this->entityManager->remove($item);
            $this->entityManager->flush();
            $this->fm->add($arr['MessageSuccess']);

        } catch (\Exception $ex){
            $this->fm->status = 'error';
            $this->fm->add($arr['MessageError'] . $ex->getMessage());
        }
        return $this->redir($arr['Redirect']);
    }
}

class BaseController extends BaseAdminController
{
    protected $auth;
    public function __construct($entityManager, AuthenticationService $authenticationService = null)
    {
        parent::__construct($entityManager);
        if (isset($authenticationService)){
            $this->auth = $authenticationService;
        }
    }
    public function onDispatch(MvcEvent $e)
    {
        if (isset($this->auth)){
            if (!$this->auth->hasIdentity()){
                return $this->redirect()->toRoute('auth-doctrine',['controller' => 'index', 'action' => 'login']);
            }
        }
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }
}
