<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;

$r->headLink()->appendStylesheet('/css/izv.css');
$r->headLink()->appendStylesheet('/css/upload.css');
$r->headLink()->appendStylesheet('/css/jsrecord.css');
//$r->headScript()->appendFile('/js/ui/jquery-ui.min.js');
//$r->inlineScript()->captureStart();
//echo <<<JS
//    $(function() {
//      $('.date').datepicker();
//    });
//JS;
//$r->inlineScript()->captureEnd();
/**
 * @var \Zend\Form\Element $el
 */
$el = null;
/**
 * @var \Custom\MyForm $form
 */
$form = null;
$bclass = 'form-horizontal col-lg-6';
$cclass = '';
$lclass = 'pd-10 control-label';

if (empty($status)){
    $act = '/izv/all/add/?name=notice';
//    if (isset($num)){
//        $act .= '&num='.$num;
//    }
    echo $r->partial('loadFile.phtml',['act' => $act]);
}
echo "<form>";
$main = new \Custom\BaseView($r,'main','w100');
$main->addFields("Общие данные");

$bv = new \Custom\BaseView($r, 'izvAdd1', 'form-horizontal col-lg-6 c-b');
//$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('usrFirstName'), ['lclass' => $lclass.' col-lg-6',
//    'eclass' => $cclass.' col-lg-6', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('numberIzv'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('date'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('mailto'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('applicability'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$i1 = $bv->pr();

$bv = new \Custom\BaseView($this, 'izvAdd2', 'form-horizontal col-lg-6 c-b');
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('reason'), ['lclass' => $lclass.' col-lg-3',
    'eclass' => $cclass.' col-lg-9', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('zadel'), ['lclass' => $lclass.' col-lg-3',
    'eclass' => $cclass.' col-lg-9', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('impl'), ['lclass' => $lclass.' col-lg-3',
    'eclass' => $cclass.' col-lg-9', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('department'), ['lclass' => $lclass.' col-lg-3',
    'eclass' => $cclass.' col-lg-9', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('appendix'), ['lclass' => $lclass.' col-lg-3',
    'eclass' => $cclass.' col-lg-9', 'class' => 'form-group']));
$i2 = $bv->pr();

$main->addInCol($i1);
$main->addInCol($i2);
echo $main->pr();
$main = new \Custom\BaseView($r,'main1','w100');
$main->addFields("Содержание изменения");
if (count($this->vals) > 0) {
    $main->addInCol($r->partial('izv-content.phtml', ['act' => 'Действие', 'cont' => 'Примечание:', 'page' => 1]));
}
$main->addInCol("<div id=\"save\" class=\"w100 dn\"><a class='btn btn-success m-2mm fr bold pd-2' href='#'>Сохранить</a></div>");
$main->addInCol("<div id=\"create\" class=\"w100 dn\"><a class='btn btn-success m-2mm fr bold pd-2' href='#'>Создать</a></div>");
echo $main->pr();
echo "</form>";
if (count($this->vals) > 0) {
    $rec = new \Custom\BaseView($r, 'recs', 'bn c-w pl-15px pr-15px');
    $rec->addInCol($r->partial('head-content.phtml'));
    foreach ($this->vals as $val) {
        $val['link'] = $this->path . '&pdf=' . $val['link'];
//        $par = [];
//        if (is_array($val)) {
//            $par['link'] = $this->path . '&pdf=' . $val[1];
//            $par['name'] = $val[0];
//        } else {
//            $par['link'] = $this->path . '&pdf=' . $val;
//            $par['name'] = $val;
//        }
        $rec->addInCol($r->partial('record.phtml', $val));
    }
    echo $rec->pr();
}


