<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;

$r->headLink()->appendStylesheet('/css/izv.css');
$r->headLink()->appendStylesheet('/css/upload.css');
$r->headLink()->appendStylesheet('/css/jsrecord.css');
/**
 * @var \Zend\Form\Element $el
 */
$el = null;
/**
 * @var \Custom\MyForm $form
 */
$form = null;
$bclass = 'form-horizontal col-lg-6';
$cclass = 'pd-10';
$lclass = 'pd-10 control-label';

if (empty($status)){
   echo $r->partial('loadFile.phtml',['act' => '/izv/all/add/?name=notice']);
}

$bv = new \Custom\BaseView($r, 'izvAdd1', 'form-horizontal col-lg-4');
//$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('usrFirstName'), ['lclass' => $lclass.' col-lg-6',
//    'eclass' => $cclass.' col-lg-6', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('numberIzv'), ['lclass' => $lclass.' col-lg-6',
    'eclass' => $cclass.' col-lg-6', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('date'), ['lclass' => $lclass.' col-lg-6',
    'eclass' => $cclass.' col-lg-6', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('applicability'), ['lclass' => $lclass.' col-lg-6',
    'eclass' => $cclass.' col-lg-6', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('mailto'), ['lclass' => $lclass.' col-lg-6',
    'eclass' => $cclass.' col-lg-6', 'class' => 'form-group']));
echo $bv->pr();

$bv = new \Custom\BaseView($this, 'izvAdd2', 'form-horizontal col-lg-8');
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('reason'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('zadel'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('impl'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('department'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
$bv->addInCol(\Custom\BaseView::createEl($r, $this->form->getEl('appendix'), ['lclass' => $lclass.' col-lg-4',
    'eclass' => $cclass.' col-lg-8', 'class' => 'form-group']));
echo $bv->pr();

    ?>

<div class="main hidden">
    <div class="border dib m" style="border-bottom: none; width: 185mm;">
        <div class="fl">
            <div class="border tac" style="width: 15mm; margin: -1px 0 0 -1px;">1</div>
        </div>
        <div class="fl" style="width: 90%;">
            <div class="tac">
                <div id="name" class="dib">КЭВ-П4040Е.00.000</div>
                <div id="act" class="dib">Заменить</div>
            </div>
            <div id="cont" class="dib" style="width: 100%; margin-left: 5mm">a</div>
        </div>
    </div>
</div>

<div class="bn c-w">
<table class="w100 bn">
    <tr class="bn">
        <th class="w15">Номер чертежа</th>
        <th class="w15">Действие</th>
        <th class="w60">Примечание (содержание изменения)</th>
        <th class="w10"></th>
    </tr>
</table></div>
<?php foreach ($this->vals as $val) {
    echo $r->partial('record.phtml');
}?>
