<div class="border dib m w100 bb-n br-n bl-n">
    <div class="fl">
        <div class="border tac pd-2 bt-n bl-n" style="width: 15mm; margin: -1px 0px 0px -1px;"><?=$this->EscapeHtml($this->num)?></div>
    </div>
    <div class="fl" style="width: 90%;">
        <div class="tac pd-2">
            <div id="name" class="dib"><?=$this->EscapeHtml($this->name)?></div>
            <div id="act" class="dib"><?=$this->EscapeHtml($this->act)?></div>
        </div>
        <div id="cont" class="dib pd-2 w100" style=" margin-left: 5mm"><?=$this->EscapeHtml($this->cont)?></div>
    </div>
</div>