<?php
ob_start();
echo "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><title>Document</title><link rel='stylesheet' media='print' href='css/print.css'></head><body>";
$this->headLink(['rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'])->appendStylesheet('/css/izv.css');
$c = "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><title>Document
    </title><link rel='stylesheet' media='all' href='css/print.css'></head><body>";
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;

foreach ($this->cont as $k=>$items) {
    $bv = new \Custom\BaseView($r, 'main', 'Main fs-0');
    $bv->addPrefixDiv('subMain pr');
    $bv->addPostfixDiv();
    if ($k == 1)
    {
        $bv->head($this->par);
        $foot = new \Custom\BaseView($r,"foot",'w100 pa bottom-0');
        $foot->foot($this->foot);
        $bv->addInCol($foot->pr());
    }
    else {
        $bv->head1($this->par, $k);
    }
    $bv->headIzm();
    foreach ($items as $item) {
        $bv->addInCol($r->partial('izv-content-pdf.phtml',$item));
    }
    $c .= $bv->pr();
}

$c .= "</body></html>";
echo $c;

$cont = ob_get_clean();
$fn = uniqid() . '.html';
$fout = 't' . '.pdf';
file_put_contents(\Custom\Exec::$path . $fn, $cont);
$cmd = new \Custom\Exec('wkhtmltopdf', ['--margin-top 0mm --margin-bottom 0mm --margin-left 0mm --margin-right 0mm --zoom 1.5',
    \Custom\Exec::$path . $fn, \Custom\Exec::$path . $fout]);
$cmd->runExec();
rename(\Custom\Exec::$path . $fout, \Custom\Exec::$contMovePath . 'izv\\' . $this->par['name'].'.pdf');
unlink(\Custom\Exec::$path.$fn);
ob_end_clean();
echo json_encode(['success' => 1,'link' => '/izv/all/show/?path=izv/&pdf=' . $this->par['name'].'.pdf']);
exit;
//file_force_download(\Custom\Exec::$contMovePath . $fout);

function file_force_download($file) {
    if (file_exists($file)) {
        // сбрасываем буфер вывода PHP, чтобы избежать переполнения памяти выделенной под скрипт
        // если этого не сделать файл будет читаться в память полностью!
        if (ob_get_level()) {
            ob_end_clean();
        }
        // заставляем браузер показать окно сохранения файла
        header('Content-Description: File Transfer');
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename=' . basename($file));
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        // читаем файл и отправляем его пользователю
        readfile($file);
        exit;
    }
}
