<?php
ob_start();
echo "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><title>Document</title><link rel='stylesheet' href='css/izv.css'></head><body>";
$this->headLink(['rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'])->appendStylesheet('/css/izv.css');
$cont = null;
echo "<div class=\"Main\">";
echo "<div class=\"container0\">";
echo $this->partial('head.phtml', $this->head);
echo $this->partial('contentHead.html',  $this->head);
echo "<div class=\"w100\" style='height: 175mm;'>";
echo $this->partialLoop('content.phtml', [
    array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1', 'cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
    array('name' => 'КЭВ-П4040E.00.000', 'act' => 'заменить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
    array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
    array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '3','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
    array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
    array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '2','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А
            Примечание: Изменено количество пазов на фланце, введен вид А"),

]);
echo "</div>";
echo $this->partial('foot1.phtml', $this->foot);
echo "</div>";
echo "</div>";

$this->headLink()->appendStylesheet('/css/jsrecord.css');
$this->headScript()->appendFile('/js/hiddenPrint.js');
echo "</body></html>";
$cont = ob_get_clean();
echo $cont;
$fn = uniqid() . '.html';
$fout = 'test' . '.pdf';
file_put_contents(\Custom\Exec::$path . $fn, $cont);
$cmd = new \Custom\Exec('wkhtmltopdf', ['--margin-top 0mm --margin-bottom 0mm --margin-left 0mm --margin-right 0mm',
    \Custom\Exec::$path . $fn, \Custom\Exec::$path . $fout]);
$cmd->runExec();
rename(\Custom\Exec::$path . $fout, \Custom\Exec::$contMovePath . $fout);
unlink(\Custom\Exec::$path.$fn);
file_force_download(\Custom\Exec::$contMovePath . $fout);
//    ob_start ();
//    header('Content-type: application/pdf');
//    header('Content-Disposition: attachment; filename="test.pdf"');
//    $c = file_get_contents(\Custom\Exec::$contMovePath . $fout);
//
//    ob_end_flush ();


function file_force_download($file) {
    if (file_exists($file)) {
        // сбрасываем буфер вывода PHP, чтобы избежать переполнения памяти выделенной под скрипт
        // если этого не сделать файл будет читаться в память полностью!
        if (ob_get_level()) {
            ob_end_clean();
        }
        // заставляем браузер показать окно сохранения файла
        header('Content-Description: File Transfer');
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename=' . basename($file));
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        // читаем файл и отправляем его пользователю
        readfile($file);
        exit;
    }
}
