<?php
ob_start();
echo "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><title>Document</title><link rel='stylesheet' media='print' href='css/print.css'></head><body>";
$this->headLink(['rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'])->appendStylesheet('/css/izv.css');
$c = "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><title>Document
    </title><link rel='stylesheet' media='all' href='css/print.css'></head><body>";
$cont = null; $h = 5.5;
$par = ['cause' => 'Введение конструктивных улучшений', 'list' => '&nbsp', 'listov' => '1', 'date' => '30.11.17',
    'dep' => 'КБВиГ', 'desc' => 'см. ниже', 'name' => 'ТПМШ.001-18', 'code' => '1', 'zadel' =>'&nbsp', 'vn' => '&nbsp',
    'inherit' => '&nbsp', 'mailto' => 'Учтенным абонентам', 'attach' => '2 эл черт в PDF; 2 развертки дет. в DXF'];
$r = $this;
$style = ['line-height' => $h . 'mm'];
$style1 = ['line-height' => $h*2 . 'mm'];
$style3 = ['line-height' => 10 . 'mm'];
$style4 = ['line-height' => 5 . 'mm'];
$style5 = ['line-height' => 15.3 . 'mm'];
$style6 = ['line-height' => 20 . 'mm'];

$bv = new \Custom\BaseView($r, 'main', 'Main fs-0');
$bv->addPrefixDiv('subMain');
$bv->addPostfixDiv();
$bv->head($par);
$bv->headIzm();
$c .= $bv->pr();

$bv = new \Custom\BaseView($r, 'main1', 'Main fs-0');
$bv->addPrefixDiv('subMain');
$bv->addPostfixDiv();
$bv->head1($par);
$bv->headIzm();
$c .= $bv->pr();

$c .= "</body></html>";
echo $c;

$cont = ob_get_clean();
$fn = uniqid() . '.html';
$fout = 'test' . '.pdf';
file_put_contents(\Custom\Exec::$path . $fn, $cont);
$cmd = new \Custom\Exec('wkhtmltopdf', ['--margin-top 0mm --margin-bottom 0mm --margin-left 0mm --margin-right 0mm --zoom 1.5',
    \Custom\Exec::$path . $fn, \Custom\Exec::$path . $fout]);
$cmd->runExec();
rename(\Custom\Exec::$path . $fout, \Custom\Exec::$contMovePath . $fout);
//unlink(\Custom\Exec::$path.$fn);
file_force_download(\Custom\Exec::$contMovePath . $fout);
//    ob_start ();
//    header('Content-type: application/pdf');
//    header('Content-Disposition: attachment; filename="test.pdf"');
//    $c = file_get_contents(\Custom\Exec::$contMovePath . $fout);
//
//    ob_end_flush ();


function file_force_download($file) {
    if (file_exists($file)) {
        // сбрасываем буфер вывода PHP, чтобы избежать переполнения памяти выделенной под скрипт
        // если этого не сделать файл будет читаться в память полностью!
        if (ob_get_level()) {
            ob_end_clean();
        }
        // заставляем браузер показать окно сохранения файла
        header('Content-Description: File Transfer');
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename=' . basename($file));
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        // читаем файл и отправляем его пользователю
        readfile($file);
        exit;
    }
}
