<div class="pa bottom-0 m-1">
    <table class="table3">
        <tr>
            <td class="cell-4"><?=$this->EscapeHtml($this->addKey)?></td>
            <td class="cell-1"><?=$this->EscapeHtml($this->addValue)?></td>
            <td class="cell-5"></td>
            <td class="cell-5"><?=$this->EscapeHtml($this->CreateDate)?></td>
            <td class="cell-1"><?=$this->EscapeHtml($this->Key4)?></td>
            <td class="cell-1"><?=$this->EscapeHtml($this->Val4)?></td>
            <td class="cell-5"></td>
            <td class="cell-5"></td>
        </tr>
        <tr>
            <td><?=$this->EscapeHtml($this->Key1)?></td>
            <td><?=$this->EscapeHtml($this->Val1)?></td>
            <td></td>
            <td></td>
            <td><?=$this->EscapeHtml($this->Key5)?></td>
            <td><?=$this->EscapeHtml($this->Val5)?></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><?=$this->EscapeHtml($this->Key2)?></td>
            <td><?=$this->EscapeHtml($this->Val2)?></td>
            <td></td>
            <td></td>
            <td><?=$this->EscapeHtml($this->Key6)?></td>
            <td><?=$this->EscapeHtml($this->Val6)?></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><?=$this->EscapeHtml($this->Key3)?></td>
            <td><?=$this->EscapeHtml($this->Val3)?></td>
            <td></td>
            <td></td>
            <td><?=$this->EscapeHtml($this->Key7)?></td>
            <td><?=$this->EscapeHtml($this->Val7)?></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="4">Измен.внес</td>
            <td><?=$this->EscapeHtml($this->Key8)?></td>
            <td><?=$this->EscapeHtml($this->Val8)?></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>
