<div class="container1 m-1">
    <table class="table1">
        <tr style="height: 15mm">
            <td class="cell-1">1</td>
            <td class="cell-1">1a</td>
            <td colspan="2">2 Извещение</td>
            <td colspan="4">3 Обозначение</td>
        </tr>
        <tr style="height: 12mm">
            <td colspan="2"></td>
            <td class="cell-2">5 Срок изм.</td>
            <td class="cell-3" rowspan="2">6</td>
            <td class="cell-4" rowspan="2">7</td>
            <td class="cell-5" rowspan="2">8 Лист</td>
            <td  rowspan="2" colspan="2">9 Листов</td>
        </tr>
        <tr style="height: 8mm">
            <td colspan="2">4а</td>
            <td >5а</td>
        </tr>
        <tr style="height: 10mm">
            <td colspan="2">Причина</td>
            <td colspan="3">10</td>
            <td colspan="3">11 Код</td>
        </tr>
        <tr style="height: 10mm">
            <td rowspan="2" colspan="2">Указание о заделе</td>
            <td colspan="6">12</td>
        </tr>
        <tr style="height: 10mm">
            <td colspan="6">12а</td>
        </tr>
        <tr style="height: 10mm">
            <td rowspan="2" colspan="2">Указание о внедрении</td>
            <td colspan="6">13</td>
        </tr>
        <tr style="height: 10mm">
            <td colspan="6">13а</td>
        </tr>
        <tr style="height: 10mm">
            <td colspan="2">Применяемость</td>
            <td colspan="6">14</td>
        </tr>
        <tr style="height: 10mm">
            <td colspan="2">Разослать</td>
            <td colspan="6">15</td>
        </tr>
        <tr style="height: 10mm">
            <td colspan="2">Приложение</td>
            <td colspan="6">16</td>
        </tr>
    </table>
</div>