<div class="border m-1" style="display: block; width: 185mm;">
    <div class="pd-2 border tac m-1" style="display: inline-block; width: 15mm;"><pre>
            ИЗВЕЩЕНИЕ
            <?=$this->EscapeHtml($this->izv)?>
        </pre></div>
    <div class="pd-2 tac" style="display: inline-block; width: 90%;"></div>
    <div class="pd-2 tac" style="display: inline-block; width: 90%;">Лист <?=$this->EscapeHtml($this->list)?></div>
</div>