<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;
$this->headLink()->appendStylesheet('/css/btnstyle.css');
$this->headScript()->appendFile('/js/btnstyle.js');
if (isset($default)){

    foreach ($default as $item) {
        $url = $this->base . '?name='.$item[0];
        echo "<h2><a href=\"{$url}\">{$item[1]}</a><br></h2>";
    }
    echo "<a href=\"show/\">Показать</a><br><br>";
    echo "<a href=\"/izv/all/pr/\">Просмотр</a><br><br>";
    echo "<a href=\"/izv/all/download/\">Скачать pdf</a><br><br>";
    return;
}
//if(isset($desc)) echo "<h2>{$desc}</h2>";
echo "<a class='btn-sm btn-success' href=\"{$this->add}\">Добавить</a><br>";
$this->fm->pr();
$this->q->prTable();
$e =  $this->paginationControl($this->name, 'Sliding', 'pagination_control', ['route' => $this->route]);
$e = str_replace('?page', $this->table.'&page', $e);
echo $e;
?>