<h1>Извещения</h1>
<a href="/izv/add/">Добавить</a><br><br>
<?php
    /**
     * @var \Custom\FlashMsgr $fm
     */
    $fm->pr();
?>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <?php
        foreach ($ths as $th) {
                echo "<th>{$th}</th>";
            }
        ?>
    </tr>
    <?php
    foreach ($izv as $item){
        $category = $item->getCategory();
        if ($category){
            $catName = $category->getCategoryName();
        } else {
            $catName = '';
        }
        if ($item->getIsPublic()){
            $isPublic = "Да";
        } else {
            $isPublic = "Нет";
        }
        echo "<tr>
            <td>{$item->getId()}</td>
            <td>{$catName}</td>
            <td>{$item->getTxt()}</td>
            <td>{$isPublic}</td>";
        echo '<td><a href="'.$this->url('izv', array('action' => 'edit', 'id' => $item->getId())).'">Редактировать</a>&nbsp;&nbsp;
            <a href="'.$this->url('izv', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Удалить запись?\'))
            { document.location = this.href; } return false;">Удалить</a></td>';
    }
    ?>
    </tbody>
</table>

<?php
    echo $this->paginationControl($izv, 'Sliding', 'pagination_control', ['route' => 'izv']);
?>



