<div class="main oh borCol-w ma br-a bb-a bl-a" style="width: 185mm;">
    <div id="base" class="bt-a dib m borCol-i w100 record">
        <div class="fl lh-7mm">
            <div id="page" class="bb-a br-a w-13 tac borCol-i"><?=$this->EscapeHtml($this->page)?></div>
        </div>
        <div class="fl w90">
            <div class="tac lh-7mm">
                <a id="link" target="_blank" href="<?=$this->EscapeHtml($this->link)?>">
                    <div id="name" class="dib"><?=$this->EscapeHtml($this->numberIzv)?></div>
                </a>
                <div id="act" class="dib"><?=$this->EscapeHtml($this->act)?></div>
            </div>
            <div id="cont" class="dib w100 lh-5mm" style="margin-left: 5mm"><?=$this->cont?></div>
        </div>
    </div>
</div>