<div id="base" class="bt-a dib m borCol-i w100 record">
    <div class="fl lh-7mm fs">
        <div id="page" class="bb-a br-a w-13 tac borCol-i">1</div>
    </div>
    <div class="fl w90 fs">
        <div class="tac lh-7mm">
            <div id="name" name="name" class="dib"><?=$this->EscapeHtml($this->numberIzv)?></div>
            <div id="act" name="act" class="dib"><?=$this->EscapeHtml($this->act)?></div>
        </div>
        <div id="cont" name="cont" class="dib w100 lh-5mm" style="margin-left: 5mm"><?=$this->cont?></div>
    </div>
</div>