<form id="upload" action="<?= $this->EscapeHtml($this->act) ?>" method="post" enctype="multipart/form-data">
    <!--    <h3>Файлы:</h3> <br>-->
    <div class="w100" style="height: 20mm;">
        <div class="fr m-5"><input class="btn btn-success bold fs" type="submit" value="Загрузить"></div>
        <div class="fr file-upload m-5">
            <label>
                <input type="file" name="upload[]" multiple onchange="getFileName ();" id="uploaded-file">
                <span class="c-b fs">Прикрепить</span>
            </label>
        </div>
        <div id="clear" class="fr m-5"><input class="btn btn-error bold fs" type="button" value="Очистить"></div>
    </div>
</form>