<?php
    ob_start();
    $this->headLink(['rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'])->appendStylesheet('/css/izv.css');
    $cont = null;
    $bv = new \Custom\BaseView($this, 'main');
    $bv->setClass('bb-a w100 dib bc-n');
    $bv->addDiv('div.phtml', ['class' => 'fl br-a', 'style' => "width:65mm;height:10mm;", 'cont' => "ИЗВЕЩЕНИЕ"]);
    $bv->addDiv('div.phtml', ['class' => 'fl', 'style' => "width:auto;", 'cont' => "ОБОЗНАЧЕНИЕ"]);
    $c = $bv->pr();
    echo $c;

//    echo "<div class=\"Main\">";
//    echo "<div class=\"container0\">";
//    echo $this->partial('head.phtml', $this->head);
//    echo $this->partial('contentHead.html',  $this->head);
//    echo "<div class=\"w100\" style='height: 175mm;'>";
//        echo $this->partialLoop('content.phtml', [
//            array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1', 'cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//            array('name' => 'КЭВ-П4040E.00.000', 'act' => 'заменить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//            array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//            array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '3','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//            array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//            array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '2','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А
//            Примечание: Изменено количество пазов на фланце, введен вид А"),
//
//        ]);
//    echo "</div>";
//    echo $this->partial('foot1.phtml', $this->foot);
//    echo "</div>";
//    echo "</div>";

//
//    echo "<div class=\"Main\">";
//    echo "<div class=\"container0\">";
//    echo $this->partial('head1.phtml', $head);
//    echo $this->partial('contentHead.html', $head);
//    echo "<div class=\"main border m-1\">";
//    echo $this->partialLoop('content.phtml', [
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1', 'cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'заменить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '3','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '2','cont' => "Примечание: Изменено количество пазов на фланце, введен вид А
//                Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1', 'cont' => "Примечание: Изменено количество пазов на фланце, введен вид А
//                Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1', 'cont' => "Примечание: Изменено количество пазов на фланце, введен вид А
//                Примечание: Изменено количество пазов на фланце, введен вид А"),
//        array('name' => 'КЭВ-П4040E.00.000', 'act' => 'добавить', 'num' => '1', 'cont' => "Примечание: Изменено количество пазов на фланце, введен вид А
//                Примечание: Изменено количество пазов на фланце, введен вид А"),
//    ]);
//    echo "</div>";
//    echo $this->partial('foot1.phtml', $foot);
//    echo "</div>";
//    echo "</div>";

    $this->headLink()->appendStylesheet('/css/jsrecord.css');
    $this->headScript()->appendFile('/js/hiddenPrint.js');
    echo "</body></html>";
    $cont = ob_get_clean();
    echo $cont;
