<?php
    ob_start();
    $this->headLink(['rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'])->appendStylesheet('/css/izv.css');
    $c = "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><title>Document
    </title><link rel='stylesheet' media='all' href='css/print.css'></head><body>";
    $r = $this;

    $bv = new \Custom\BaseView($r, 'main', 'Main fs-0');
    $bv->addPrefixDiv('subMain');
    $bv->addPostfixDiv();
    $bv->head($this->par);
    $bv->headIzm();
    $c .= $bv->pr();
    $bv = null;

    $bv = new \Custom\BaseView($r, 'main1', 'Main fs-0');
    $bv->addPrefixDiv('subMain');
    $bv->addPostfixDiv();
    $bv->head1($this->par);
    $bv->headIzm();
    $c .= $bv->pr();

    $c .= "</body></html>";
    echo $c;

    $this->headLink()->appendStylesheet('/css/jsrecord.css');
    $this->headScript()->appendFile('/js/hiddenPrint.js');
    echo "</body></html>";
    $cont = ob_get_clean();
    echo $cont;


