<div class="record">
    <div class="va">
        <div class="fl w15 va form-group-sm"><a href="#"><input class="w100 form-control" type="text" title="#"></a></div>
        <div class="fl w15 va form-group-sm">
            <select class="w100 form-control" name="" id="" title="#">
                <option value="">заменить</option>
                <option value="">добавить</option>
            </select>
        </div>
        <div class="fl w60 va form-group-sm"><textarea class="w100 form-control" style="height: 30px;" title="#"></textarea>
        </div>
        <div class="fl w10 form-group-sm"><input class="btn btn-default form-control w100" type="button" id="dob" value="Добавить"></div>
    </div>
</div>