<hr />
<table class="table">
    <tr>
        <th>Имя пользователя</th>
        <th>Пароль</th>
        <th>Email</th>
    </tr>

<?php
foreach ($users as $user) { ?>
    <tr>
        <td><?= $this->escapeHtml($user->getUsrName());?></td>
        <td><?= $this->escapeHtml($user->getUsrPassword());?></td>
        <td><?= $this->escapeHtml($user->getUsrEmail());?></td>
    </tr>
 <?php   } ?>
</table>
