<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Teplomash')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'png', 'href' => $this->basePath() . '/img/Arrow.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/script.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/arrow.png') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;<b>Тепломаш</b>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('Zend\\Navigation\\Default')->menu()->setUlClass('nav navbar-nav')->render(); ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/admin/">Admin</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= '<div class="breadcrumbs"> <br>'. $this->navigation('Zend\\Navigation\\Admin_navigation')->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render() . '</div>';?>
            <?= $this->content ?>
            <hr>
            <footer class="container">
                <p>&copy; 1992 - <?= date('Y') ?> Teplomash. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
