<h2>Паспорт админка</h2>
<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $r
 */
$r = $this;
$r->headLink()->appendStylesheet('/css/izv.css');
$r->headLink()->appendStylesheet('/css/upload.css');
$this->headLink()->appendStylesheet('/css/btnstyle.css');
if (isset($default)){

    echo $r->partial('loadFile.phtml',['act' => '/passport/admin/upload/?name=passport']);
    foreach ($default as $item) {
        $url = $this->base . '?name='.$item[0];
        echo "<a class='btn btn-default' style='margin: 10px;' href=\"{$url}\">{$item[1]}</a>";
    }
//    echo "<a href=\"{$this->show}\">Показать</a><br><br>";
    return;
}
if(isset($desc)) echo "<h2>{$desc}</h2>";
echo "<a href=\"{$this->add}\">Добавить</a><br><br>";
$this->fm->pr();
$this->q->prTable();
$e = $this->paginationControl($this->name, 'Sliding', 'pagination_control', ['route' => $this->route]);
$e = str_replace('?page', $this->table.'&page', $e);
echo $e;
$this->headScript()->appendFile('/js/btnstyle.js');
?>