<?php
/**
 * Created by PhpStorm.
 * User: Simanov
 * Date: 22.11.2017
 * Time: 12:19
 */

namespace Izv\Controller;


use Custom\BaseController;
use Zend\Mvc\MvcEvent;

class AdminController extends BaseController
{
    /**
     * @var array $config
     */
    public $config;
    /**
     * @var $model
     */
    protected $model;
    /**
     * @var $path
     */
    protected $path;
    public function __construct($entityManager, $authenticationService, $config)
    {
        $this->config = $config;
        $this->path = $this->config['Path'];
        parent::__construct($entityManager, $authenticationService);
    }
    public function onDispatch(MvcEvent $e)
    {
        $this->model = $this->findModel();
        $this->model = $this->config[$this->model];
        if (empty($this->model)) {
            foreach ($this->config as $k => $item) {
                if (is_array($item)) {
                    $this->names[$k][0] = $k;
                    $this->names[$k][1] = $item['desc'];
                }
            }
        }
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $c = $this->params()->fromQuery('count');
        if (empty($c)) $c = 20;
        return $this->index($this->model, $c);
    }
    public function addAction()
    {
        return $this->add($this->model);
    }
    public function addItemAction()
    {
        return $this->itemAdd($this->model, $this->config[$this->model['refTable']]);
    }
    public function deleteItemAction()
    {
        $id = $this->params()->fromQuery('id');
        return $this->deleteItem($this->config['templates'], $id);
    }
    public function collectionAction()
    {

    }
    public function editAction()
    {
        return $this->edit($this->model);
    }
    public function deleteAction()
    {
        return $this->delete($this->model);
    }
    public function showAction()
    {
        $p = $this->params()->fromQuery()['pdf'];
        if (isset($p)) $pdf = true;
        return $this->upload($this->path . 'izv/' . $p, $pdf);
    }
}