<div class="bs-docs-section">
    <div class="well">

<?php
    $form->setAttribute('action', $this->url('admin/category', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
        echo '<fieldset><legend>Добавление категории</legend>';
        foreach ($form as $element){
            echo '<div class="form-group">';
            $attr = $element->getAttributes();
            if ($element->getLabel()){
                $element->setLabelAttributes(['class' => 'col-lg-2 control-label']);
                if (isset($attr['required'])){
                    $element->setLabel($element->getLabel() . ' *');
                }
            }
            if (isset($attr['type']) && $attr['type'] == 'text'){
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formInput($element);
                echo '</div>';
            } elseif (isset($attr['type']) && $attr['type'] == 'textarea') {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formTextArea($element);
                echo '</div>';
            } elseif (isset($attr['type']) && $attr['type'] == 'file') {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formFile($element);
                echo '</div>';
            } else {
                echo '<div class="col-lg-10">';
                echo $this->formRow($element);
                echo '</div>';
            }
        }
        echo '</<fieldset>';
        echo $this->form()->closeTag();
?>
    </div>
</div>
